version: "3.3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ollitape
      - DB_USER=devuser
      - DB_PASS=changeme

  db:
    image: mysql:8.0-debian
    ports:
      # - "0.0.0.0:3306:3306/tcp"
      - "3306:3306"
    volumes:
      # - ./mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./build/libs/:/usr/local/tomcat/webapps/
    environment:
      - MYSQL_DATABASE=ollitape
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=thisisnotsafe


## volumes:
##   mysql-data:
