apiVersion: apps/v1 
kind: Deployment
metadata:
  name: login-deployment 
  labels:
    tier: back-end
    service: login
    env: dev
spec:
  template:
    metadata:
      name: main-pod 
      labels:
        tier: back-end
        service: login
        env: dev
    spec:
      containers:
        - name: login-microservice
          image: rommelrodperez/buffetapp:login
          command: ["sh","-c"]
          args: ["python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          env:
          - name: DB_HOST
            value: logindb
          - name: DB_NAME
            value: devdb
          - name: DB_USER
            value: mainapp
          - name: DB_PASS
            value: changeme
      imagePullSecrets:
        - name: regcred
  replicas: 1 
  selector:
    matchLabels:
      env: dev