apiVersion: apps/v1 
kind: Deployment
metadata:
  name: login-deployment 
  labels:
    tier: back-end
    service: login
    env: dev
spec:
  template:
    metadata:
      name: main-pod 
      labels:
        tier: front-end
        env: dev
    spec:
      containers:
        - name: webdev-app
          image: mysql:8.0-debian
  replicas: 2 
  selector:
    matchLabels:
      env: dev