apiVersion: v1
kind: Service
metadata:
  name: temp-login-access 
spec:
  type: NodePort
  ports:
    - nodePort: 30800 
      targetPort: 8000  
      port: 80 
  selector:
    tier: back-end
    service: login
    env: dev