apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
    - nodePort: 30080 
      targetPort: 8080  
      port: 80 
  selector:
    tier: front-end
    env: dev